version: '3'
services:
  db:
    image: devops_db
    build: 
      context: ./db
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
    depends_on:
      - db

  api:
    image: devops_api
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  web:
    image: devops_web
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - api
