version: '3'
services:
  mongodb:
    image: db_devops:v1.0.1
    restart: always
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
    ports:
      - 8081:8081
    depends_on:
      - mongodb

  backend:
    image: backend_devops:v1.0.1
    container_name: backend
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - mongodb

  frontend:
    image: frontend_devops:v1.0.1
    container_name: frontend
    restart: always
    environment:
      - API_URI=http://backend:5000/api/topics
    ports:
      - 3000:3000
    depends_on:
      - backend
