version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: TopicstoreDb
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_AUTHENTICATION_DATABASE: admin
    ports:
      - 27017:27017
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - 8081:8081
    depends_on:
      - mongodb

  backend:
    image: jorhak/backend_devops:v1.0.0
    container_name: backend
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - mongodb

  frontend:
    image: jorhak/frontend_devops:v1.0.0
    container_name: frontend
    restart: always
    environment:
      - API_URI=http://backend:5000/api/topics
    ports:
      - 3000:3000
    depends_on:
      - backend
