#!/bin/bash
DOCKER_HUB_LOGIN_USER=jorhak
DOCKER_HUB_LOGIN_PASSWORD=?BarbaraLee_
IMAGE_BACKEND=backend_devops
IMAGE_FRONTEND=frontend_devops
IMAGE_DB=db_devops
VERSION=v1.0.1
REGISTRY=jorhak

docker login --username=$DOCKER_HUB_LOGIN_USER --password=$DOCKER_HUB_LOGIN_PASSWORD
docker tag $IMAGE_BACKEND:$VERSION $REGISTRY/$IMAGE_BACKEND:$VERSION
docker tag $IMAGE_FRONTEND:$VERSION $REGISTRY/$IMAGE_FRONTEND:$VERSION
docker tag $IMAGE_DB:$VERSION $REGISTRY/$IMAGE_DB:$VERSION

docker push $REGISTRY/$IMAGE_BACKEND:$VERSION
docker push $REGISTRY/$IMAGE_FRONTEND:$VERSION
docker push $REGISTRY/$IMAGE_DB:$VERSION
