#!/bin/bash
DOCKER_HUB_LOGIN_USER=
DOCKER_HUB_LOGIN_PASSWORD=
IMAGE_BACKEND=backend_devops
IMAGE_FRONTEND=frontend_devops
VERSION=v1.0.0
REGISTRY=jorhak

docker login --username=$DOCKER_HUB_LOGIN_USER --password=$DOCKER_HUB_LOGIN_PASSWORD
docker tag $IMAGE_BACKEND:$VERSION $REGISTRY/$IMAGE_BACKEND:$VERSION
docker tag $IMAGE_FRONTEND:$VERSION $REGISTRY/$IMAGE_FRONTEND:$VERSION

docker push $REGISTRY/$IMAGE_BACKEND:$VERSION
docker push $REGISTRY/$IMAGE_FRONTEND:$VERSION
